# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmatimes_app', '0002_auto_20160428_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
